version: '3.8'
services:
  php-fpm:
    image: kedubuis/php-fpm:001
    volumes:
      - path:/var/www/app

  nginx:     
    image: kedubuis/nginx:001
    ports:
      - "2020:80"
      - "2222:2222"
    volumes:
      - path:/var/www/app
      
